[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
tokio.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
murmur3.workspace = true

[dev-dependencies]
crossbeam-utils = "0.8.21"
